### ISSUE TITLE
Permission denied error when deploying

### ISSUE THREAD

**Issue by Sam-Max** [iPromKnight/zilean#1]
Hi, I am getting this permission denied error on the logs, when trying to deploy zilean:

----------------------------
 ---> System.IO.IOException: Permission denied
 ---> System.UnauthorizedAccessException: Access to the path '/app/data/lucene' is denied.
System.IO.IOException: Cannot create directory: /app/data/lucene/DMM
   --- End of inner exception stack trace ---
-------------------

**Comment by prom3theu5** [comment]
are you using a custom volume mount for the data dir?
You have to ensure that you have write permissions on the folder
quite fix is `chmod -R 777 /path/to/data`

**Comment by iPromKnight** [comment]
are you using a custom volume mount for the data dir?
You have to ensure that you have write permissions on the folder
quite fix is chmod -R 777 /path/to/data

**Comment by nykdev** [comment]
You need to give permissions to your docker container, add this to your compose file 
environment:
      - PUID=1000
      - PGID=1000
    user: "${PUID}:${PGID}"

**Comment by iPromKnight** [comment]
I've updated the compose example in the repo: https://github.com/iPromKnight/zilean/blob/main/compose.yaml

**Comment by Sam-Max** [comment]
> I've updated the compose example in the repo: https://github.com/iPromKnight/zilean/blob/main/compose.yaml

Ok, thanks, now is working.

**Comment by Sam-Max** [comment]
> I've updated the compose example in the repo: https://github.com/iPromKnight/zilean/blob/main/compose.yaml

**Comment by Sam-Max** [comment]
> I've updated the compose example in the repo: https://github.com/iPromKnight/zilean/blob/main/compose.yaml

another question, when I make a post request to the /dmm/search endpoint using a query, like a movie name,  I get this response:{"type":"https://tools.ietf.org/html/rfc9110#section-15.6.1","title":"An error occurred while processing your request.","status":500,"detail":"this IndexWriter is disposed.\\nObject name: \'Lucene.Net.Index.IndexWriter\'."}

**Comment by iPromKnight** [comment]
Thansk fixed now :)
Please pull latest, and ensure you either delete your data folder, or your data volume
